### PR TITLE
Update lv_sjpg.c

### PR DESCRIPTION
**Pull request by reusu**

### CODE REVIEW

**Comment by reusu** [comment]
[https://github.com/lvgl/lv_lib_split_jpg/issues/29](url)

**Comment by kisvegabor** [comment]
Looks good, thank your for the fix.

@cmumford can you take a look at the failing CI?

**Comment by cmumford** [comment]
> @cmumford can you take a look at the failing CI?

I believe the problem is that the pull_request action uses lukka/run-cmake@v3 to do the cmake build, and the push action directly invokes cmake. cmake needs to be directly invoked because lukka/run-cmake@v3 ignores `ExternalProject_add` which is how lvgl is downloaded and built. The solution is to make pull_request like pull. I'll upload a PR shortly.

**Comment by kisvegabor** [comment]
Thank you, Chris.

**Comment by kisvegabor** [comment]
@cmumford fixed the issue of the CI. As it's very unlikely that this PR will cause any issue I merge it as it is. We will see the result of the updated CI after merge.

**Comment by kisvegabor** [comment]
Aaand all passed.  Thank you for both of you! :slightly_smiling_face:

**Pull request merged**
