### PR TITLE
fix: check raw_sjpeg_data  before strcmp

### PR DESCRIPTION
**Pull request by wendal**
1. init lvgl
2. init sjpeg decoder
3. call lv_canvas_create ==> crash

### CODE REVIEW

**Comment by kisvegabor** [comment]
I don't understand what problem it solves. `(src)->data` and `(src)->data_size` should be valid if you pass a pointer to valid `lv_img_dsc_t`.

**Comment by wendal** [comment]
in lv_canvas_create

```c
    /*Initialize the allocated 'ext' */
    ext->dsc.header.always_zero = 0;
    ext->dsc.header.cf          = LV_IMG_CF_TRUE_COLOR;
    ext->dsc.header.h           = 0;
    ext->dsc.header.w           = 0;
    ext->dsc.data_size          = 0;
    ext->dsc.data               = NULL;

    lv_img_set_src(new_canvas, &ext->dsc);
```

everything is NULL or 0

**Comment by wendal** [comment]
So, shall we fix lv_canvas_create , not this decoder ?

**Comment by wendal** [comment]
BTW, I use lv_bmp and lv_png too, at the same project. only lv_sjpg crash on this case.

**Comment by kisvegabor** [comment]
Ah, got it now, thanks. 

It think LVGL should return earlier if sees an incomplete or invalid image data. I've added fix [here](https://github.com/lvgl/lvgl/commit/d0c1c673a8ec17b842ebf97d5f21938ec8901346). Please confirm if it works well there too.

**Comment by wendal** [comment]
that is better ^_^

**Pull request closed without merging**
