### PR TITLE
Make the example program buildable.

### PR DESCRIPTION
**Pull request by cmumford**
Modify the example program, demo_jpg_sjpg, so that it can compile
and link. Doing this will make it easier to detect required changes
when LVGL is changed, as well as function as a simple test program
for this project.

### CODE REVIEW

**Review by embeddedt — COMMENTED** [review]
Perhaps this should probably be wrapped in an `#if LV_LIB_SJPG_TEST` guard, to prevent this `main` from being linked into real applications?

**Comment by cmumford** [comment]
The upcoming CMakeLists.txt will create a library for this project, so desktop apps won't even be including this file, and I'm pretty sure that a ESP-IDF build won't include this either. Maybe you're thinking of [lv_demos](https://github.com/lvgl/lv_demos), which have no main(), and are [included elsewhere](https://github.com/lvgl/lv_port_esp32/blob/master/main/main.c#L32-L44)?

I'm happy to add the `#ifdef`, but wanted to understand how you envisioned it being used?

**Comment by cmumford** [comment]
Just noticed I confused lv_demos and lv_examples, but still am curious how this would be used.

**Comment by kisvegabor** [comment]
> Perhaps this should probably be wrapped in an #if LV_LIB_SJPG_TEST guard, to prevent this main from being linked into real applications?

E.g. I use Eclipse that automatically collects all the C files. Therefore there would be 2 `main()` functions. 
You can exclude certain folders from build, but we should make the project work out of box without any extra configuration.

**Comment by cmumford** [comment]
That makes sense. I'll upload a new version.

**Comment by kisvegabor** [comment]
Looks good, merging.

**Pull request merged**
