### PR TITLE
Upgrade to TJpgDec R0.03.

### LINKED ISSUE #16: TJpgDec R0.03 has been released
TJpgDec R0.03 was released July 1, 2021 and is available at http://elm-chan.org/fsw/tjpgd/00index.html.

I tested this on desktop, and seems as stable as the prior releases. Upgrading to R0.02a was discussed in https://github.com/lvgl/lv_lib_split_jpg/issues/14, but @kisvegabor wanted to fix https://github.com/lvgl/lv_lib_split_jpg/issues/12 (ASAN issue) first. I think we can close https://github.com/lvgl/lv_lib_split_jpg/issues/14 and target an upgrade to R0.03.

### PR DESCRIPTION
**Pull request by cmumford**
Upgrade the JPEG decoder (TJpgDec) from R0.01d to R0.03 released
July 1, 2021.

This is a copy of TJpgDec downloaded from the authoritative site:
http://elm-chan.org/fsw/tjpgd/00index.html.

This fixes https://github.com/lvgl/lv_lib_split_jpg/issues/16

### CODE REVIEW

**Comment by cmumford** [comment]
Note: I have compiled this for desktop and ESP-IDF, but don't have a device handy to test on an ESP32 (or other MCU).

**Comment by kisvegabor** [comment]
I've tested it on my Linux notebook and it was working well. I couldn't test for regression in performance or memory usage but I think we can assume they are quite the same as before.

So I merge it. Thank you @cmumford.

Are there any other open issues?

**Comment by cmumford** [comment]
Nope - thx for the testing.

I'm working on creating a GitHub workflow to build and test the project. I do have a few questions about how to implement it, so I'll open an issue to discuss with you before sending any PR's.

**Comment by kisvegabor** [comment]
> I'm working on creating a GitHub workflow to build and test the project. I do have a few questions about how to implement it, so I'll open an issue to discuss with you before sending any PR's.

It'd be amazing. We could reuse it for the other similar repos  (PNG, BMP, QRcode, FreeType, etc)

**Pull request merged**
