### PR TITLE
Add CMake ESP-IDF build file.

### PR DESCRIPTION
**Pull request by cmumford**
Add a top-level CMake project file to create a component for this repo.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Thanks! 

I think once we add a Cmake file we should add a "general case" too. Something like [here](https://github.com/lvgl/lvgl/blob/master/CMakeLists.txt#L61-L66).

Do you agree?

**Comment by cmumford** [comment]
Agreed. I also made [one](https://github.com/cmumford/lv_lib_split_jpg/blob/common-cmake/CMakeLists.txt) this weekend which builds for Linux and Windows. Unfortunately it looks like GitHub Workflows (or maybe [lukka/run-cmake](https://github.com/lukka/run-cmake)) don't support CMake's [ExternalProject](https://cmake.org/cmake/help/latest/module/ExternalProject.html). I use that to clone and build LVGL. Once I have a clean solution to that problem I'll send out another PR.

**Comment by kisvegabor** [comment]
Can we add the [linked Cmake file](https://github.com/cmumford/lv_lib_split_jpg/blob/common-cmake/CMakeLists.txt) too?

**Comment by cmumford** [comment]
Hi @kisvegabor . Yes, I'm definitely going to complete the CMake file - as well as create a GitHub workflow. I want to make sure it does what you need. I created https://github.com/lvgl/lv_lib_split_jpg/issues/24, as I expect a few questions. If you're OK with what I propose there, then I'll complete the work. As part of this effort I plan on making the [example](https://github.com/lvgl/lv_lib_split_jpg/tree/master/example) fully buildable. Also, once we're happy with the CMake file then I can do the same work in other LVGL projects. I'll close this PR as this component CMake file has landed.

**Pull request closed without merging**
